<?php
/**
 * Ibrams_CmsExtended extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Ibrams
 * @package        Ibrams_CmsExtended
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<div class="content-header">
    <h3 class="icon-head head-categories">
        <?php echo $this->escapeHtml($this->getHeader()) . ($this->getCmspageId() ? ' (' . Mage::helper('ibrams_cmsextended')->__('ID: %s', $this->getCmspageId()) . ')' : '') ?>
    </h3>
    <p class="content-buttons form-buttons">
        <?php echo $this->getResetButtonHtml() ?>
        <?php if ($this->getCmspageId()): ?>
            <?php echo $this->getDeleteButtonHtml() ?>
        <?php endif; ?>
        <?php echo $this->getAdditionalButtonsHtml(); ?>
        <?php echo $this->getSaveButtonHtml() ?>
    </p>
</div>
<?php echo $this->getTabsHtml() ?>
<iframe name="iframeSave" style="display:none; width:100%;" src="<?php echo $this->getJsUrl() ?>blank.html"></iframe>
<form target="iframeSave" id="cmspage_edit_form" action="<?php echo $this->getSaveUrl() ?>" method="post" enctype="multipart/form-data">
    <div class="no-display">
        <input type="hidden" name="isIframe" value="1" />
        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
        <input type="hidden" name="active_tab_id" id="active_tab_id" value="" />
        <input type="hidden" name="cmspage_products" id="in_cmspage_products" value="" />
        <input type="hidden" name="cmspage_categories" id="in_cmspage_categories" value="" />
    </div>
    <div id="cmspage_tab_content"></div>
</form>
<script type="text/javascript">
//<![CDATA[
    cmspageForm = new varienForm('cmspage_edit_form');
    cmspageForm.submit= function (url) {
        this.errorSections = $H({});
        this.canShowError = true;
        this.submitUrl = url;
        if (this.validator && this.validator.validate()) {
            if (this.validationUrl) {
                this._validate();
            } else {
                if (this.isSubmitted) {
                    return false;
                }
                this.isSubmitted = true;
                this._submit();
            }
            displayLoadingMask();
            return true;
        }
        return false;
    };
    cmspageForm.refreshPath = function () {
        cmspageId = this.getCmspageId();
        if (!cmspageId) {
            return false;
        }
        var refreshPathSuccess = function(transport) {
            if (transport.responseText.isJSON()) {
                response = transport.responseText.evalJSON()
                if (response.error) {
                    alert(response.message);
                } else {
                    if (cmspageForm.getCmspageId() == response['id']) {
                        cmspageForm.setCmspagePath(response['path']);
                    }
                }
            }
        };
        new Ajax.Request(
            '<?php echo $this->getRefreshPathUrl() ?>',
            {
                method: 'POST',
                evalScripts: true,
                onSuccess: refreshPathSuccess
            }
        );
    };

    cmspageForm.getCmspageId = function () {
        collection = $(this.formId).getInputs('hidden', 'cmspage[id]');
        if (collection.size() > 0) {
            return collection.first().value;
        }
        return false;
    };
    cmspageForm.setCmspagePath = function (path) {
        collection = $(this.formId).getInputs('hidden', 'cmspage[path]');
        if (collection.size() > 0) {
            return collection.first().value = path;
        }
    };
    function cmspageSubmit(url, useAjax) {
        var activeTab = $('active_tab_id');
        if (activeTab) {
            if (activeTab.tabsJsObject && activeTab.tabsJsObject.activeTab) {
                activeTab.value = activeTab.tabsJsObject.activeTab.id;
            }
        }
        var params = {};
        var fields = $('cmspage_edit_form').getElementsBySelector('input', 'select');
        for(var i=0;i<fields.length;i++) {
            if (!fields[i].name) {
                continue;
            }
            params[fields[i].name] = fields[i].getValue();
        }
        var cmspageId = params['cmspage[id]'] ? params['cmspage[id]'] : 0;
        var isCreating = cmspageId == 0;
        var path = params['cmspage[path]'].split('/');
        var parentId = path.pop();
        if (parentId == cmspageId) {
            parentId = path.pop();
        }
        if (isCreating) {
            if (!tree.currentNodeId) {
                tree.currentNodeId = parentId;
            }
            tree.addNodeTo = parentId;
        } else {
            var currentNode = tree.getNodeById(cmspageId);
            var oldClass = 'active-category';
            var newClass = 'active-category';
            if (currentNode) {
                if (parseInt(params['cmspage[status]'])) {
                    var oldClass = 'no-active-category';
                    var newClass = 'active-category';
                } else {
                    var oldClass = 'active-category';
                    var newClass = 'no-active-category';
                }
                Element.removeClassName(currentNode.ui.wrap.firstChild, oldClass);
                Element.addClassName(currentNode.ui.wrap.firstChild, newClass);
            }
        }
        cmspageForm.submit();
    }
    <?php if (($block = $this->getLayout()->getBlock('cmspage.product.grid')) && ($_gridJsObject=$block->getJsObjectName())): ?>
        var cmspageProducts = $H(<?php echo $this->getProductsJson() ?>);
        $('in_cmspage_products').value = cmspageProducts.toQueryString();
        function registerCmspageProduct(grid, element, checked) {
        if (checked) {
            if (element.positionElement) {
                element.positionElement.disabled = false;
                cmspageProducts.set(element.value, element.positionElement.value);
            }
        } else {
            if (element.positionElement) {
                element.positionElement.disabled = true;
            }
            cmspageProducts.unset(element.value);
        }
        $('in_cmspage_products').value = cmspageProducts.toQueryString();
            grid.reloadParams = {'selected_products[]':cmspageProducts.keys()};
        }
        function cmspageProductRowClick(grid, event) {
            var trElement = Event.findElement(event, 'tr');
            var isInput   = Event.element(event).tagName == 'INPUT';
            if (trElement) {
                var checkbox = Element.getElementsBySelector(trElement, 'input');
                if (checkbox[0]) {
                    var checked = isInput ? checkbox[0].checked : !checkbox[0].checked;
                    <?php echo $_gridJsObject ?>.setCheckboxChecked(checkbox[0], checked);
                }
            }
        }
        function positionChange(event) {
            var element = Event.element(event);
            if (element && element.checkboxElement && element.checkboxElement.checked) {
            cmspageProducts.set(element.checkboxElement.value, element.value);
                $('in_cmspage_products').value = cmspageProducts.toQueryString();
            }
        }
        var tabIndex = 1000;
        function cmspageProductRowInit(grid, row) {
            var checkbox = $(row).getElementsByClassName('checkbox')[0];
            var position = $(row).getElementsByClassName('input-text')[0];
            if (checkbox && position) {
                checkbox.positionElement = position;
                position.checkboxElement = checkbox;
                position.disabled = !checkbox.checked;
                position.tabIndex = tabIndex++;
                Event.observe(position, 'keyup', positionChange);
            }
        }
        <?php echo $_gridJsObject ?>.rowClickCallback = cmspageProductRowClick;
        <?php echo $_gridJsObject ?>.initRowCallback = cmspageProductRowInit;
        <?php echo $_gridJsObject ?>.checkboxCheckCallback = registerCmspageProduct;
        <?php echo $_gridJsObject ?>.rows.each(function(row) {
            cmspageProductRowInit(<?php echo $_gridJsObject ?>, row)
        });
    <?php endif; ?>
    <?php if ($this->isAjax() && ($block = $this->getLayout()->getBlock('tabs')) && ($_tabsJsObject=$block->getJsObjectName())): ?>
        <?php echo $_tabsJsObject ?>.moveTabContentInDest();
        if (<?php echo $_tabsJsObject ?>.activeTab) {
            $('active_tab_id').value = <?php echo $_tabsJsObject ?>.activeTab.id;
        }
        $('active_tab_id').tabsJsObject = <?php echo $_tabsJsObject ?>;
    <?php endif; ?>
//]]>
</script>
