<?php
/**
 * Ibrams_CmsExtended extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Ibrams
 * @package        Ibrams_CmsExtended
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Cmspage children list template
 *
 * @category    Ibrams
 * @package     Ibrams_CmsExtended
 * @author      Ultimate Module Creator
 */
?>
<?php $_cmspages = $this->getCmspages(); ?>
<?php if ($_cmspages->getSize() > 0) :?>
    <div class="page-title cmspage-title">
        <h2><?php echo $this->getCurrentCmspage()->getName(); ?>:<?php echo $this->__('Children')?></h2>
    </div>
    <?php if ($this->_getDisplayMode() == 0) : ?>
        <div class="cmspage-list-container">
            <?php foreach ($_cmspages as $_cmspage) : ?>
                <div class="cmspage-list-item">
                    <a href="<?php echo $_cmspage->getCmspageUrl();?>" title="<?php echo $this->escapeHtml($_cmspage->getName()) ?>">
                        <?php echo $_cmspage->getName(); ?>
                    </a>
                </div>
            <?php endforeach;?>
        </div>
    <?php else : ?>
        <ul id="cmspages-list">
            <?php foreach ($_cmspages as $_cmspage) : ?>
                <?php echo $this->drawCmspage($_cmspage);?>
            <?php endforeach;?>
        </ul>
        <script type="text/javascript">
            cmsextendedTree('cmspages-list');
        </script>
    <?php endif;?>
<?php endif;?>
