<?php 
/**
 * Ibrams_CmsExtended extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Ibrams
 * @package        Ibrams_CmsExtended
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Cmspage list template
 *
 * @category    Ibrams
 * @package     Ibrams_CmsExtended
 * @author      Ultimate Module Creator
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_cmspages = $this->getCmspages(); ?>
<div class="page-title cmspage-title">
    <?php if (Mage::helper('ibrams_cmsextended/cmspage')->isRssEnabled()) : ?>
        <a href="<?php echo Mage::helper('ibrams_cmsextended/cmspage')->getRssUrl();?>" class="link-rss"><?php echo Mage::helper('ibrams_cmsextended')->__('Subscribe to RSS Feed')?></a>
    <?php endif;?>
    <h1><?php echo Mage::helper('ibrams_cmsextended')->__('Cmspages') ?></h1>
</div>
<?php if ($_cmspages->getSize() > 0) :?>
    <?php if ($this->_getDisplayMode() == 0) : ?>
        <?php echo $this->getPagerHtml(); ?>
        <div class="cmspage-list-container">
            <?php foreach ($_cmspages as $_cmspage) : ?>
                <div class="cmspage-list-item">
            <a href="<?php echo $_cmspage->getCmspageUrl()?>">
                <?php echo $_cmspage->getName();?>
            </a><br />
                </div>
            <?php endforeach;?>
        </div>
        <?php echo $this->getPagerHtml(); ?>
    <?php else : ?>
        <ul id="cmspages-list">
            <?php foreach ($_cmspages as $_cmspage) : ?>
                <?php echo $this->drawCmspage($_cmspage);?>
            <?php endforeach;?>
        </ul>
        <script type="text/javascript">
            cmsextendedTree('cmspages-list');
        </script>
    <?php endif;?>
<?php else : ?>
    <?php echo Mage::helper('ibrams_cmsextended')->__('There are no cmspages at this moment');?>
<?php endif;?>
