<?php
/**
 * Ibrams_CmsExtended extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Ibrams
 * @package        Ibrams_CmsExtended
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Cmspage view template
 *
 * @category    Ibrams
 * @package     Ibrams_CmsExtended
 * @author      Ultimate Module Creator
 */
?>
<?php $_cmspage = $this->getCurrentCmspage();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title cmspage-title">
    <h1><?php echo $_cmspage->getName(); ?></h1>
</div>
<div class="cmspage-view">
    <div class="cmspage-name">
        <?php echo Mage::helper('ibrams_cmsextended')->__('name');?>:<?php echo $_cmspage->getName();?>
    </div>

    <div class="cmspage-htmlcontent">
        <?php echo Mage::helper('ibrams_cmsextended')->__('htmlcontent');?>:<?php echo $_cmspage->getHtmlcontent();?>

    </div>
    <div class="cmspage-author">
        <?php echo Mage::helper('ibrams_cmsextended')->__('author');?>:<?php echo $_cmspage->getAuthor();?>

    </div>

</div>
