<?php
/**
 * Ibrams_CmsExtended extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Ibrams
 * @package        Ibrams_CmsExtended
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Cmspage link widget template
 *
 * @category    Ibrams
 * @package     Ibrams_CmsExtended
 * @author      Ultimate Module Creator
 */
?>
<?php $_cmspage = $this->getCurrentCmspage();?>
<?php if ($_cmspage) :?>
    <div class="cmspage-widget-link">
        <a href="<?php echo $_cmspage->getCmspageUrl()?>"><?php echo $_cmspage->getName()?></a>
    </div>
<?php endif;?>
