<?php
/**
 * Ibrams_CmsExtended extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Ibrams
 * @package        Ibrams_CmsExtended
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Cmspage subtree template
 *
 * @category    Ibrams
 * @package     Ibrams_CmsExtended
 * @author      Ultimate Module Creator
 */
?>
<?php $_cmspages = $this->getCmspages(); ?>
<?php if ($_cmspages->getSize() > 0) :?>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/ibrams_cmsextended/tree.js')?>"></script>
    <ul id="<?php echo $this->getUniqueId()?>">
        <?php foreach ($_cmspages as $_cmspage) : ?>
            <?php echo $this->drawCmspage($_cmspage);?>
        <?php endforeach;?>
    </ul>
    <script type="text/javascript">
        cmsextendedTree('<?php echo $this->getUniqueId()?>');
    </script>
<?php endif;?>
