<?php
/**
 * Ibrams_CmsExtended extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Ibrams
 * @package        Ibrams_CmsExtended
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Page list template on product page
 *
 * @category    Ibrams
 * @package     Ibrams_CmsExtended
 * @author      Ultimate Module Creator
 */
?>
<?php $pages = $this->getPageCollection();?>
<?php if ($pages && $pages->count() > 0) :?>
<div class="box-collateral box-pages box-up-sell">
    <?php foreach ($pages as $_page) : ?>
        <div class="item">
            <a href="<?php echo $_page->getPageUrl()?>">
                <?php echo $_page->getName();?>
            </a><br />
        </div>
    <?php endforeach; ?>
</div>
<?php endif;?>
