<?php
/**
 * @category    Bubble
 * @package     Bubble_CmsTree
 * @version     1.2.1
 * @copyright   Copyright (c) 2013 BubbleCode (http://shop.bubblecode.net)
 */

/** @var $this Bubble_CmsTree_Block_Page_Html_Topmenu */
$_cmsIsFirst = !$this->hasCategoriesNavigationMenuPages();
$_categoriesIsLast = !$this->hasCmsNavigationMenuPages();
$_menu  = $this->renderCategoriesMenuHtmlBubble(0, $_categoriesIsLast, true, 'level-top');
if ($this->shouldRenderPages()) {
    $_menu .= $this->renderCmsMenuHtml(0, true, $_cmsIsFirst, 'level-top');
}
?>
<?php if ($_menu): ?>
    <div class="nav-container">
        <ul id="nav">
            <?php echo $_menu ?>
        </ul>
    </div>
<?php endif ?>